[package]
name = "rustopoly"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
console_error_panic_hook = "0.1.7"
futures = "0.3.30"
gloo-timers = { version = "0.3.0", features = ["futures"] }
js-sys = "0.3.69"
leptos = { version = "0.7.0-beta", features = ["csr", "nightly"] }
leptos_router = { version = "0.7.0-beta", features = ["nightly"] }
serde = "1.0.204"
serde-wasm-bindgen = "0.6.5"
tailwind-merge = { version = "0.1.0", path = "../tailwind-merge" }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
