[package]
name = "rustopoly"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
gloo-timers = { version = "0.3.0", features = ["futures"] }
js-sys = "0.3.69"
leptos = { version = "0.7.0-beta", features = ["csr", "nightly"] }
leptos_router = { version = "0.7.0-beta", features = ["nightly"] }
serde = "1.0.204"
serde-wasm-bindgen = "0.6.5"
snafu = "0.8.4"
tailwind-merge = { version = "0.1.0", path = "../tailwind-merge" }
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = "0.3.18"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"

[profile.dev.package.backtrace]
opt-level = 3
