[package]
name = "server"
version = "0.1.0"
edition = "2021"


[dependencies]
shared = { path = "../shared" }
tokio = { workspace = true }
tarpc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
snafu = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-subscriber = { workspace = true }
