[package]
name = "isolog"
version = "0.1.0"
edition = "2021"

[target.'cfg(all(target_arch = "wasm32",not(any(target_os = "emscripten", target_os = "wasi"))))'.dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = ["console"] }
